spring.application.name=deets

spring.datasource.url=jdbc:postgresql://localhost:5432/urls
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.base-url=http://localhost:8080

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health, metrics
spring.redis.host=localhost
spring.redis.port=6379
